jobs:
  ci:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-v1-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile --cache-folder ~/.cache/yarn

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - add_ssh_keys:
         fingerprints:
            - "cb:e7:71:c8:f4:3f:ab:1a:7a:41:d8:d3:35:b8:7f:61"
      - deploy:
          name: axiome-NAS
          command: ssh -p 3456 -t sunjay@192.168.1.110 "touch /home/sunjay/testproduction/nuxtapp/sunnykumar.txt;"

workflows:
  version: 2
  ci:
    jobs:
      - ci:
          filters:
            branches:
              only:
                - main
                - master
                - developer
