jobs:
  ci:
    docker:
      - image: cimg/node:lts
    steps:
      - add_ssh_keys:
          fingerprints:
            - "3c:07:49:16:fd:56:8e:bc:c0:31:2e:c5:4f:f7:02:91"
      - checkout

      - run:
          name: Setup
          command: |
            chmod 755 .circleci/deploy.sh
          #sudo ssh-keyscan -vvv -H -p 3456 192.168.1.110 >> ~/.ssh/known_hosts

      - restore_cache:
          keys:
            - yarn-v1-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile --cache-folder ~/.cache/yarn

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Deploy
          command: .circleci/deploy.sh
workflows:
  version: 2
  ci:
    jobs:
      - ci:
          filters:
            branches:
              only:
                - main
                - master
                - developer
