jobs:
  ci:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-v1-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile --cache-folder ~/.cache/yarn

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - add_ssh_keys:
         fingerprints:
            - "9d:53:7f:ca:ff:c7:38:8f:c5:95:42:4a:bb:af:42:af"
      - deploy:
          name: axiome-NAS
          command: ssh -vvv -p 22 -t sunjay@192.168.1.110 "cd /home/sunjay;"

workflows:
  version: 2
  ci:
    jobs:
      - ci:
          filters:
            branches:
              only:
                - main
                - master
                - developer
