jobs:
  ci:
    docker:
      - image: cimg/node:lts
    steps:
      - add_ssh_keys:
          fingerprints:
            - "be:01:9d:8b:5a:aa:7b:30:0f:17:ef:cb:ad:36:5d:fc"
      - checkout

      - run:
          name: Setup
          command: |
            chmod 755 .circleci/deploy.sh
            chmod 755 ~/.ssh
            ssh-keyscan -v -H -p 3456 49.0.71.34 >> ~/.ssh/known_hosts
            ssh-copy-id -p 3456 sunjay@49.0.71.34

      - restore_cache:
          keys:
            - yarn-v1-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile --cache-folder ~/.cache/yarn

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Deploy
          command: .circleci/deploy.sh
workflows:
  version: 2
  ci:
    jobs:
      - ci:
          filters:
            branches:
              only:
                - main
                - master
                - developer
