jobs:
  ci:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-v1-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile --cache-folder ~/.cache/yarn

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - add_ssh_keys:
         fingerprints:
            - "9d:53:7f:ca:ff:c7:38:8f:c5:95:42:4a:bb:af:42:af"
      - run:
          name: add to known hosts
          command: |
            sudo ssh-keyscan -H -p 22 192.168.1.110 >> ~/.ssh/known_hosts
            sudo echo "192.168.1.110 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIS7N6RGFZlmqTjQ2wYAKxSIN3QDBm41Mj6FQxUuFtwB sunnythai786@gmail.com" >> ~/.ssh/known_hosts

workflows:
  version: 2
  ci:
    jobs:
      - ci:
          filters:
            branches:
              only:
                - main
                - master
                - developer
