jobs:
  ci:
    docker:
      - image: cimg/node:lts
    steps:
      - add_ssh_keys:
          fingerprints:
            - "d1:b8:09:5b:12:08:ea:5f:54:9a:42:06:df:9c:67:ab"
      - checkout

      - run:
          name: Setup
          command: |
            chmod 755 .circleci/deploy.sh
            sudo ssh-keyscan -vvv -H -p 3456 192.168.1.110 >> ~/.ssh/known_hosts

      - restore_cache:
          keys:
            - yarn-v1-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile --cache-folder ~/.cache/yarn

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Yarn Build
          command: yarn Build
      - run:
          name: Deploy
          command: .circleci/deploy.sh
workflows:
  version: 2
  ci:
    jobs:
      - ci:
          filters:
            branches:
              only:
                - main
                - master
                - developer
